kind: pipeline
type: docker
name: default
   
steps:
  - name: install
    image: node:18
    commands:
      - npm install -g npm@latest 
        && npm install

  - name: lint
    image: node:18
    commands:
      - npm run lint
    when:
      branch:
      - main
      - dev

  - name: build
    image: node:18
    commands:
      - npm run dist
    when:
      branch:
      - main
      - dev

  - name: test
    image: node:18
    commands:
      - apt-get update 
      - npx puppeteer browsers install chrome
      - npm run test
    when:
      branch:
      - main
      - dev

  - name: npm
    image: plugins/npm
    settings:
      token: 
        from_secret: npm_token
    when:
      event:
      - tag

